#!/usr/bin/env bash
set -euo pipefail

# Concatenate all non-test Go files in the repo into a single file.
# Usage: scripts/merge_go.sh [OUTPUT_FILE]

out="${1:-merged_go_sources.txt}"

# Truncate/create the output file
: > "$out"

# Collect Go source files excluding tests and common cache/vendor dirs
tmp_list="$(mktemp)"
find . \
  -type f -name '*.go' \
  -not -name '*_test.go' \
  -not -path './test/*' \
  -not -path './vendor/*' \
  -not -path './.gomodcache/*' \
  -not -path './.gocache/*' \
  -not -path './.git/*' \
  | sort > "$tmp_list"

count=$(wc -l < "$tmp_list" | tr -d '[:space:]')
if [ "$count" = "0" ]; then
  echo "No Go files found to merge." >&2
  rm -f "$tmp_list"
  exit 1
fi

{
  echo "// Merged Go sources (non-test)"
  echo "// Generated by scripts/merge_go.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo
} >> "$out"

while IFS= read -r f; do
  echo "// ===== BEGIN $f =====" >> "$out"
  cat "$f" >> "$out"
  echo >> "$out"
  echo "// ===== END $f =====" >> "$out"
  echo >> "$out"
done < "$tmp_list"

rm -f "$tmp_list"

echo "Wrote $count files into $out"
